import { Inter } from "next/font/google";
import { ThemeProvider } from "../components/ThemeProvider";
import "./globals.css";
import SmoothScrolling from "@/components/SmoothScrolling";
import Navbar from "@/components/section/Navbar";
import Footer from "@/components/section/Footer";
import Transition from "@/components/section/Transition";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <SmoothScrolling> */}

        <ThemeProvider>
          <Transition />
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>

        {/* </SmoothScrolling> */}
      </body>
    </html>
  );
}
